intro_room_beginning = "To level up from adventure rank F, you go into a dungeon. But uh oh rocks slide down, covering the dungeon entrance and blocking the way out of the cave. But since this is a fantasy world, you can get out of dungeons by going to the last room in the dungeon. However, there are a bunch of mobs blocking your way. Additionally, you got lucky and the amount of mobs in this cave is perfectly the amount of mobs you need to level up from adventure rank F to adventure rank D. So, you set off into the dungeon and pray not to get hurt in the dungeon."
room_1beg = "This is the first room and there are 3 slimes in this room. They are blocking a chest. Defeat all the mobs and you can open the chest. After beating the mobs in this room, there are two ways you can go: east or south."
room_2beg = "This is the second room and there are 3 skeletons in this room. After beating the room, there are two ways you can go; either back up to the room before or the room south of this one."
room_3beg = "This is the third room and there are 3 spiders in this room. After beating the room, there are three ways you can go; either to the room before or the room east of this one or the room north of this one."
room_4beg = "This is the fourth room and there are 3 boars in this room. After beating the room, there are two ways you can go; either to the room before or the room west of this one."
room_5beg = "This is the fifth room and there is one big slime and 2 slimes in this room. After beating the room, there are two ways you can go; either to the room before or the room east of this one."
room_6beg = "This is the sixth room and there are two big slimes and 2 slimes in this room. After beating the room, there are four ways you can go; the room before, to the west, to the east and to the south."
room_7beg = "This is the seventh room and there are three big slimes in this room. After beating the room, there are two ways you can go; either to the room before or the room south of this one."
room_8beg = "This is the eighth room and there is one armored skeleton and one armored orc. After beating the room, there are two ways you can go; either to the room before or the room west of this one."
room_9beg = "This is the ninth room and there are two armored skeletons and two armored orcs. This is the miniboss and the room right before the boss of this dungeon. After beating the room, there are two ways you can go; either to the room before or the room east of this one."
room_10beg = "This is the hardest room there will be in the game, if you made it this far then,  cool, after you beat this room, you probably will get out of this cave. There might be like 4 big big slimes. They have like 1000 health."


room_fall = "Uh Oh. This room was a trap for you and going into this room brings you right back to the start. This was not my idea and instead the idea of my partner. SO now you suffer because of him. RIP"
room_gambling =  "So this room gives you one free item the second you walk into it. However, you can also choose to sacrifice 25 percent of your health you have a chance at getting another item or a punishment. It's your choice :)"


afterroom_1 = "There are two ways you can go: east or south."
afterroom_2 = "There are two ways you can go: north or south."
afterroom_3 = "There are three ways you can go: west or north or east."
afterroom_4 = "There are two ways you can go: south or west"
afterroom_5 = "There are two ways you can go: west or east."
afterroom_6 = "There are four ways you can go: north or south or west or east"
afterroom_7 = "There are two ways you can go: west or south"
afterroom_8 = "There are two ways you can go: south or east"
afterroom_9 = "There are two ways you can go: west or east"
afterroom_10 = "There is one way you can go: west. If you have defeated all 10 rooms in this dungeon and you are ready to leave you can type leave to leave the dungeon."